ALTER TABLE "Deck" ADD COLUMN IF NOT EXISTS "bracket" INTEGER;
ALTER TABLE "Deck" ADD COLUMN IF NOT EXISTS "bracketSuggested" INTEGER;
ALTER TABLE "Deck" ADD COLUMN IF NOT EXISTS "bracketConfidence" TEXT;
ALTER TABLE "Deck" ADD COLUMN IF NOT EXISTS "bracketAnalysisJson" JSONB;
ALTER TABLE "Deck" ADD COLUMN IF NOT EXISTS "bracketUpdatedAt" TIMESTAMP(3);
ALTER TABLE "Deck" ADD COLUMN IF NOT EXISTS "bracketAnalyzedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Deck_bracket_idx" ON "Deck"("bracket");
